input_type: "image"
semantic_segmentation_cfg: ["resnet50", "deeplab"]
max_instances: 50
mask_opening_size: 20 # Morphology to remove False Negatives
mask_dilation_size: 20 # Morphology to expand mask
background_class_threshold: 0.66 # Threshold for backgroudn detection
foreground_class_threshold: 0.33 # Threshold for foreground detection
instance_confidence_threshold: 0.2

# class indexes
semseg_idx:
  deeplab: ['background', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus',
 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike',
 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']


# Inpainting
crfill:
  weights_path: 'weights/crfill/model_256.pth'